In [1]:
import numpy as np 
import pandas as pd

In [2]:
a = pd.read_csv('/kaggle/input/novel-corona-virus-2019-dataset/covid_19_data.csv')
a.head()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0

In [3]:
a.tail(10)

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
306419,306420,05/29/2021,Yukon,Canada,2021-05-30 04:20:55,84.0,2.0,82.0
306420,306421,05/29/2021,Yunnan,Mainland China,2021-05-30 04:20:55,352.0,2.0,331.0
306421,306422,05/29/2021,Zabaykalsky Krai,Russia,2021-05-30 04:20:55,43126.0,669.0,41650.0
306422,306423,05/29/2021,Zacatecas,Mexico,2021-05-30 04:20:55,30758.0,2797.0,0.0
306423,306424,05/29/2021,Zakarpattia Oblast,Ukraine,2021-05-30 04:20:55,61611.0,1586.0,58882.0
306424,306425,05/29/2021,Zaporizhia Oblast,Ukraine,2021-05-30 04:20:55,102641.0,2335.0,95289.0
306425,306426,05/29/2021,Zeeland,Netherlands,2021-05-30 04:20:55,29147.0,245.0,0.0
306426,306427,05/29/2021,Zhejiang,Mainland China,2021-05-30 04:20:55,1364.0,1.0,1324.0
306427,306428,05/29/2021,Zhytomyr Oblast,Ukraine,2021-05-30 04:20:55,87550.0,1738.0,83790.0
306428,306429,05/29/2021,Zuid-Holland,Netherlands,2021-05-30 04:20:55,391559.0,4252.0,0.0

In [4]:
mask = a['Confirmed'].between(19,20)
mask

0         False
1         False
2         False
3         False
4         False
          ...
306424    False
306425    False
306426    False
306427    False
306428    False
Name: Confirmed, Length: 306429, dtype: bool

In [5]:
a[mask]

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
95,96,01/24/2020,Shanghai,Mainland China,1/24/20 17:00,20.0,0.0,1.0
143,144,01/25/2020,Hainan,Mainland China,1/25/20 17:00,19.0,0.0,0.0
302,303,01/28/2020,Gansu,Mainland China,1/28/20 23:00,19.0,0.0,0.0
413,414,01/30/2020,Inner Mongolia,Mainland China,1/30/20 16:00,19.0,0.0,0.0
475,476,01/31/2020,Inner Mongolia,Mainland China,1/31/2020 23:59,20.0,0.0,1.0
...,...,...,...,...,...,...,...,...
304629,304630,05/27/2021,Montserrat,UK,2021-05-28 04:20:36,20.0,1.0,19.0
305041,305042,05/28/2021,NaN,Solomon Islands,2021-05-29 04:20:41,20.0,0.0,20.0
305394,305395,05/28/2021,Montserrat,UK,2021-05-29 04:20:41,20.0,1.0,19.0
305806,305807,05/29/2021,NaN,Solomon Islands,2021-05-30 04:20:55,20.0,0.0,20.0
306159,306160,05/29/2021,Montserrat,UK,2021-05-30 04:20:55,20.0,1.0,19.0

In [6]:
mask2 = a['ObservationDate'].between('01/22/2020','01/23/2020')
mask2

0          True
1          True
2          True
3          True
4          True
          ...
306424    False
306425    False
306426    False
306427    False
306428    False
Name: ObservationDate, Length: 306429, dtype: bool

In [7]:
a[mask2]

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
209269,209270,01/22/2021,Zaporizhia Oblast,Ukraine,2021-04-02 15:13:53,63623.0,772.0,44340.0
209270,209271,01/22/2021,Zeeland,Netherlands,2021-04-02 15:13:53,13414.0,151.0,0.0
209271,209272,01/22/2021,Zhejiang,Mainland China,2021-04-02 15:13:53,1316.0,1.0,1305.0
209272,209273,01/22/2021,Zhytomyr Oblast,Ukraine,2021-04-02 15:13:53,43186.0,720.0,39339.0
209273,209274,01/22/2021,Zuid-Holland,Netherlands,2021-04-02 15:13:53,227777.0,3236.0,0.0