In [1]:
import numpy as np 
import pandas as pd

In [2]:
a = pd.read_csv('/kaggle/input/novel-corona-virus-2019-dataset/covid_19_data.csv')
a.head()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0

In [3]:
mask = a['Country/Region'] == 'India'
a[mask]

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
446,447,01/30/2020,NaN,India,1/30/20 16:00,1.0,0.0,0.0
509,510,01/31/2020,NaN,India,1/31/2020 23:59,1.0,0.0,0.0
567,568,02/01/2020,NaN,India,1/31/2020 8:15,1.0,0.0,0.0
629,630,02/02/2020,NaN,India,2020-02-02T06:03:08,2.0,0.0,0.0
696,697,02/03/2020,NaN,India,2020-02-03T21:43:02,3.0,0.0,0.0
...,...,...,...,...,...,...,...,...
306351,306352,05/29/2021,Tripura,India,2021-05-30 04:20:55,50739.0,507.0,43190.0
306366,306367,05/29/2021,Unknown,India,2021-05-30 04:20:55,0.0,0.0,0.0
306377,306378,05/29/2021,Uttar Pradesh,India,2021-05-30 04:20:55,1688152.0,20208.0,1621743.0
306378,306379,05/29/2021,Uttarakhand,India,2021-05-30 04:20:55,327112.0,6360.0,289642.0
306406,306407,05/29/2021,West Bengal,India,2021-05-30 04:20:55,1354956.0,15268.0,1237290.0

In [4]:
mask1 = a['Country/Region'] == 'India'
mask2 = a['Country/Region'] == 'Japan'
a [mask1 | mask2]

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
35,36,01/22/2020,NaN,Japan,1/22/2020 17:00,2.0,0.0,0.0
75,76,01/23/2020,NaN,Japan,1/23/20 17:00,1.0,0.0,0.0
123,124,01/24/2020,NaN,Japan,1/24/20 17:00,2.0,0.0,0.0
166,167,01/25/2020,NaN,Japan,1/25/20 17:00,2.0,0.0,0.0
214,215,01/26/2020,NaN,Japan,1/26/20 16:00,4.0,0.0,1.0
...,...,...,...,...,...,...,...,...
306401,306402,05/29/2021,Wakayama,Japan,2021-05-30 04:20:55,2612.0,41.0,2410.0
306406,306407,05/29/2021,West Bengal,India,2021-05-30 04:20:55,1354956.0,15268.0,1237290.0
306413,306414,05/29/2021,Yamagata,Japan,2021-05-30 04:20:55,1963.0,42.0,1692.0
306414,306415,05/29/2021,Yamaguchi,Japan,2021-05-30 04:20:55,2903.0,60.0,2330.0
306416,306417,05/29/2021,Yamanashi,Japan,2021-05-30 04:20:55,1541.0,19.0,1390.0