In [1]:
import numpy as np
import pandas as pd

In [2]:
a = pd.read_csv('/kaggle/input/novel-corona-virus-2019-dataset/covid_19_data.csv')

a.head()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0

In [3]:
a['ObservationDate'] = pd.to_datetime(a['ObservationDate'])

In [4]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306429 entries, 0 to 306428
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   SNo              306429 non-null  int64
 1   ObservationDate  306429 non-null  datetime64[ns]
 2   Province/State   228326 non-null  object
 3   Country/Region   306429 non-null  object
 4   Last Update      306429 non-null  object
 5   Confirmed        306429 non-null  float64
 6   Deaths           306429 non-null  float64
 7   Recovered        306429 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 18.7+ MB

In [5]:
a['Last Update'] = pd.to_datetime(a['Last Update'], format='mixed')

In [6]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306429 entries, 0 to 306428
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   SNo              306429 non-null  int64
 1   ObservationDate  306429 non-null  datetime64[ns]
 2   Province/State   228326 non-null  object
 3   Country/Region   306429 non-null  object
 4   Last Update      306429 non-null  datetime64[ns]
 5   Confirmed        306429 non-null  float64
 6   Deaths           306429 non-null  float64
 7   Recovered        306429 non-null  float64
dtypes: datetime64[ns](2), float64(3), int64(1), object(2)
memory usage: 18.7+ MB

In [7]:
mask = a['Province/State'].isnull()

In [8]:
a[mask]

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
35,36,2020-01-22,NaN,Japan,2020-01-22 17:00:00,2.0,0.0,0.0
36,37,2020-01-22,NaN,Thailand,2020-01-22 17:00:00,4.0,0.0,2.0
37,38,2020-01-22,NaN,South Korea,2020-01-22 17:00:00,1.0,0.0,0.0
39,40,2020-01-22,NaN,Kiribati,2020-01-22 17:00:00,0.0,0.0,0.0
75,76,2020-01-23,NaN,Japan,2020-01-23 17:00:00,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...
305831,305832,2021-05-29,NaN,Vietnam,2021-05-30 04:20:55,6908.0,47.0,2896.0
305832,305833,2021-05-29,NaN,West Bank and Gaza,2021-05-30 04:20:55,307838.0,3492.0,300524.0
305833,305834,2021-05-29,NaN,Yemen,2021-05-30 04:20:55,6731.0,1319.0,3399.0
305834,305835,2021-05-29,NaN,Zambia,2021-05-30 04:20:55,94751.0,1276.0,91594.0
305835,305836,2021-05-29,NaN,Zimbabwe,2021-05-30 04:20:55,38933.0,1594.0,36578.0

In [9]:
mask2 = a['Province/State'].notnull()

In [10]:
a[mask2]

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,2020-01-22,Anhui,Mainland China,2020-01-22 17:00:00,1.0,0.0,0.0
1,2,2020-01-22,Beijing,Mainland China,2020-01-22 17:00:00,14.0,0.0,0.0
2,3,2020-01-22,Chongqing,Mainland China,2020-01-22 17:00:00,6.0,0.0,0.0
3,4,2020-01-22,Fujian,Mainland China,2020-01-22 17:00:00,1.0,0.0,0.0
4,5,2020-01-22,Gansu,Mainland China,2020-01-22 17:00:00,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
306424,306425,2021-05-29,Zaporizhia Oblast,Ukraine,2021-05-30 04:20:55,102641.0,2335.0,95289.0
306425,306426,2021-05-29,Zeeland,Netherlands,2021-05-30 04:20:55,29147.0,245.0,0.0
306426,306427,2021-05-29,Zhejiang,Mainland China,2021-05-30 04:20:55,1364.0,1.0,1324.0
306427,306428,2021-05-29,Zhytomyr Oblast,Ukraine,2021-05-30 04:20:55,87550.0,1738.0,83790.0
306428,306429,2021-05-29,Zuid-Holland,Netherlands,2021-05-30 04:20:55,391559.0,4252.0,0.0

In [11]:
mask3 = a['Province/State'].isna()

In [12]:
a[mask3]

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
35,36,2020-01-22,NaN,Japan,2020-01-22 17:00:00,2.0,0.0,0.0
36,37,2020-01-22,NaN,Thailand,2020-01-22 17:00:00,4.0,0.0,2.0
37,38,2020-01-22,NaN,South Korea,2020-01-22 17:00:00,1.0,0.0,0.0
39,40,2020-01-22,NaN,Kiribati,2020-01-22 17:00:00,0.0,0.0,0.0
75,76,2020-01-23,NaN,Japan,2020-01-23 17:00:00,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...
305831,305832,2021-05-29,NaN,Vietnam,2021-05-30 04:20:55,6908.0,47.0,2896.0
305832,305833,2021-05-29,NaN,West Bank and Gaza,2021-05-30 04:20:55,307838.0,3492.0,300524.0
305833,305834,2021-05-29,NaN,Yemen,2021-05-30 04:20:55,6731.0,1319.0,3399.0
305834,305835,2021-05-29,NaN,Zambia,2021-05-30 04:20:55,94751.0,1276.0,91594.0
305835,305836,2021-05-29,NaN,Zimbabwe,2021-05-30 04:20:55,38933.0,1594.0,36578.0